language: r
cran: http://cran.rstudio.com
cache: packages
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libv8-dev

r_github_packages:
  - jimhester/covr

after_success:
- R -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
