language: r
dist: trusty
sudo: required
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev netcdf-bin libv8-dev

r_github_packages:
  - jimhester/covr

after_success:
- R -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
