language: r
sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev libjq-dev
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - R -e 'install.packages("jsonlite", type = "source")'

r_github_packages:
  - jimhester/covr

after_success:
- R -e 'covr::codecov()'

r:
  - release
  - devel
  - oldrel

notifications:
  email:
    on_success: change
    on_failure: change
